language: objective-c
script: 
  - xctool -project example.xcodeproj -scheme exampleTests build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash -c "$(git log -1 --pretty=%B | tail -1)"
